#!/usr/bin/python3
# coding=utf8
import cv2
import numpy as np
import move as m
from ArmIK.ArmMoveIK import *

while True:
  self.AK = ArmIK()
  result = self.AK.setPitchRangeMoving((0, 0, 7), -90, -90, 0)
  print("result is "+result[2])
  time.sleep(result[2]/1000)
  if not self.isRunning:
      continue
  servo2_angle = getAngle(0, 0, 0)  # Calculate the angle by which the gripper needs to be rotated
  Board.setBusServoPulse(1, self.servo1 - 280, 500)
  Board.setBusServoPulse(2, servo2_angle, 500)
  time.sleep(0.5)
